connectTo 'jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl' 'CS347_prof' 'orcl_prof' 'rdf_mode';
SQL """ DROP TABLE TEST_DELETE """
#CREATE TABLE TEST_DELETE (VAL1 NUMBER, VAL2 NUMBER, VAL3 NUMBER)~
SQL """ INSERT INTO TEST_DELETE (VAL1, VAL2, VAL3) VALUES ('one', 2, 3) """
SQL """ INSERT INTO TEST_DELETE (VAL1, VAL2, VAL3) VALUES (1, 4, 5) """
SQL """ INSERT INTO TEST_DELETE (VAL1, VAL2, VAL3) VALUES (6, 7, 8) """
print SQL """ SELECT VAL1, VAL2 FROM TEST_DELETE WHERE VAL1 = 1 """

SQL """ DELETE FROM TEST_DELETE WHERE VAL1 = 'one'; """
SQL """ DELETE FROM TEST_DELETE WHERE 1 = VAL1; """

print SQL """ SELECT VAL1, VAL2 FROM TEST_DELETE WHERE VAL1 = 1 """

# INSERT INTO TEST_DELETE (VAL1, VAL2, VAL3) VALUES (1, 1, 1);
# print (SELECT * FROM TEST_DELETE WHERE VAL1 = 1;)
